### ISSUE TITLE
Sätt station_id om simuleringen avslutas inom stationsområde

### ISSUE THREAD

**Issue by jannikarlsson** [joki20/pattern-db#16]
Scootern får station_id om admin eller kund medvetet placerar scootern på stationen, och i triggern som sätter avgift kontrolleras om scootern är inom ett stationsområde. Men scootern får inte station_id om så är fallet, utan det påverkar bara avgiften. Triggern (eller annan trigger?) skulle även kunna sätta station_id om scootern befinner sig inom stationsområde.

**Comment by joki20** [comment]
jag har försökt få det funka att tillägna scooter till stationen den hamnar intill. Men det fungerade inte genom triggern.
När triggern kör igång och kollar igenom varje rad i scooter-tabellen efter customer_id ändras till NULL, så kan den inte ändra något i scooter-tabellen. Så det går med andra ord inte ändra station_id

Därför måste det vid en uppdatering av scooterns customer_id till NULL i frontend även kollas i frontend om scootern är intill radien av någon station.
Dvs loopa igenom stationerna och kolla om någon ligger inom 2m avstånd. Om så är fallet, sätt iscooterns station_id till stationens id.

**Comment by joki20** [comment]
sköts i frontend
