### ISSUE TITLE
Städernas mittpunkter verkar vara fel

### ISSUE THREAD

**Issue by jannikarlsson** [joki20/pattern-db#17]
Behöver uppdateras i ddl.sql och nya slumpkoordinater genereras.
![image](https://user-images.githubusercontent.com/48861971/142826322-fb6913df-5a6c-45dc-be13-59d4a11a8afb.png)

**Comment by jannikarlsson** [comment]
Och tror att radierna behöver justeras ner till ungefär hälften för alla städer!

**Comment by joki20** [comment]
Jag sätter denna som avslutad nu.
