### ISSUE TITLE
Ändra battery_level till decimal

### ISSUE THREAD

**Issue by jannikarlsson** [joki20/pattern-db#21]
Om man ska kunna sänka batteriet med en sjättedels procentenhet behöver batterinivån ändras från INT till DECIMAL. 

Vet inte hur det funkar, avrundar den själv vid insert eller måste man skicka in avrundade tal?

**Comment by joki20** [comment]
decimal avrundar atuomatiskt vid flera decimaler än tillåtet, gjort om till DECIMAL(5,2)
