### ISSUE TITLE
Payment terms-kolumnen är tom för alla rader i api/users

### ISSUE THREAD

**Issue by jannikarlsson** [joki20/pattern-db#27]
![image](https://user-images.githubusercontent.com/48861971/144901398-8e53bcba-d992-4390-b78a-2fd9dae2de90.png)

**Comment by joki20** [comment]
Fixat

**Comment by jannikarlsson** [comment]
![image](https://user-images.githubusercontent.com/48861971/145014764-4080b7e1-a201-439c-a389-d367e4f022c7.png)
Nu ligger det ett "\r" på varje som gör att vi inte kan läsa in dem

**Comment by joki20** [comment]
skumt, när jag kör (utanför docker) får jag:
![image](https://user-images.githubusercontent.com/73738545/145036419-71c6f470-76d3-42de-bffa-23604d615b80.png)

**Comment by joki20** [comment]
löst, berodde på för långt varchar
