### ISSUE TITLE
Skövdes scootrar ligger fortfarande skevt utifrån centrum

### ISSUE THREAD

**Issue by jannikarlsson** [joki20/pattern-db#30]
Skriver upp det så att vi inte glömmer, nya positioner för scootrarna behöver genereras men vi kanske behöver se över om det bara är i filen eller om vi har fel centrum på fler ställen. Uppsala och Lund ser bra ut.
![image](https://user-images.githubusercontent.com/48861971/145467228-e4cd30b4-2f77-4b7e-aafb-40f3e01e4c5c.png)

**Comment by joki20** [comment]
Fixat
