### ISSUE TITLE
Saknade decimaler?

### ISSUE THREAD

**Issue by datalowe** [joki20/pattern-db#4]
I [ddl-skriptet](https://github.com/joki20/pattern-db/blob/master/sql-scripts/ddl.sql) finns en del DECIMAL-kolumner som inte har specifikation för antal siffror/decimaler. Ex i `customer`, 

```sql
[...]
    `funds` DECIMAL DEFAULT 0,
```
Jag vet inte hur MySQL beter sig då. Är det bara placeholders, eller ska de vara 'specifikationslösa' även framöver?

**Comment by jannikarlsson** [comment]
Jag testade att skicka in koordinater i en ospecad tidigare och då tog den emot heltalen men strök alla decimaler. Så vi ska nog speca dem allihop.

**Comment by datalowe** [comment]
joki20:
> funds kan man ha kanske 7,2 som decimal (7 siffror varav 2 är decimaler)
som mest kan man ha 99999,99 på kontot då 😄

Låter bra, vi vill ju att Stockholmsbrats ska kunna vaska stålar till oss så bäst att ha lite utrymme. 

En som är mer klurig är `speed` i `scooter`-tabellen. Ska elcykeln rapportera hastighet i meter/s? km/s? @jannikarlsson Lär påverkas av det mest vid simulering, så du får gärna agera diktator här för min del.

**Comment by jannikarlsson** [comment]
Där är mos lite svävande, han menade att scootern inte behöver skicka något alls under färd men när jag sa att hastigheten då är 0 vid punkt A och 0 vid punkt B blev han lite fundersam. Hur som helst, jag tänker mig INT och kph för att hålla det enkelt, så får vi se om det klarnar.

**Comment by jannikarlsson** [comment]
Även med den nya infon tänker jag mig INT och km/h för hastigheten. Cykelklienten kan slumpa en hastighet inom ett rimligt spann, typ 0-20,  varje gång den skickar info till backend.
