### ISSUE TITLE
Använda VARCHAR eller genomgående enbart CHAR?

### ISSUE THREAD

**Issue by datalowe** [joki20/pattern-db#5]
Detaljfråga, jag vet, och spelar ingen större roll. Men om någon vill ändra det här senare blir det lite pill i Laravel också, så lika bra att bestämma nu hur vi gör.

I [ddl.sql](https://github.com/joki20/pattern-db/blob/master/sql-scripts/ddl.sql) används bara CHAR, även där man kan vänta sig att inmatade data kommer att variera i längd. Exempel:

```sql
CREATE TABLE adm
(
    `id` INT NOT NULL AUTO_INCREMENT,
    `username` CHAR(20),
    `password` CHAR(255), -- https://www.php.net/manual/en/function.password-hash.php

    PRIMARY KEY (`id`)
)
```
Många kommer nog att välja betydligt kortare användarnamn och lösenord än maxgränsen. Det är då 'best practice' att använda VARCHAR (finns detaljer i t ex [den här SO-tråden](https://stackoverflow.com/questions/59667/what-are-the-use-cases-for-selecting-char-over-varchar-in-sql)). Man sparar lite lagringsutrymme och gör key matching lite snabbare. Antagligen skulle det här göra störst skillnad för `city`-tabellen där det kanske blir aktuellt att göra sökningar på stadsnamn eller nåt, men jag misstänker att skillnaden är marginell även där iom att vi inte har några stora mängder data.

Ska vi bara ha CHAR överallt för att göra det enkelt, eller byta ut mot VARCHAR för att det ska se prydligt ut?

**Comment by joki20** [comment]
Då tycker jag att VARCHAR är lämpligare. Som sagt, vi vet aldrig hur många tecken användaren använder och dessutom blir koden mer lättläst. Jag kan sitta och fixa ddl-saker som ligger i issues under dagen.
EDIT: inte mer lättläst pga måste ange antal tecken ändå. Lösenordslängden utgick jag från bcrypt och rekommenderad hashning på 255 tecken utifrån https://www.php.net/manual/en/function.password-hash.php så därför är CHAR(255) kvar på den.

**Comment by joki20** [comment]
Fixat till detta nu, så stänger issue
