### ISSUE TITLE
DEFAULT för logg.end_time

### ISSUE THREAD

**Issue by datalowe** [joki20/pattern-db#6]
I ddl.sql

```sql
CREATE TABLE logg
(
    `id` INTEGER NOT NULL AUTO_INCREMENT,
[...]
    `start_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `end_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
[...]
)
```

Jag tänker att `end_time` borde ha DEFAULT NULL, eftersom den ska sättas först när resan tar slut. Annars kommer det bli som att resan startar och slutar vid samma tid (åtminstone tills det kommer en trigger/uppdatering). Men jag kanske missar nåt?

**Comment by jannikarlsson** [comment]
Håller med, om det inte finns något särskilt skäl till att den sätts vid start nu. Om den är NULL i stället föreställer jag mig att man lättare kan filtrera bort ej avslutade resor i historiken.
