### ISSUE TITLE
@start_cost verkar refereras till innan den satts 

### ISSUE THREAD

**Issue by datalowe** [joki20/pattern-db#7]
I [ddl. sql](https://github.com/joki20/pattern-db/blob/master/sql-scripts/ddl.sql#L140)

```sql
DROP TRIGGER IF EXISTS logg_insert;
DROP TRIGGER IF EXISTS logg_update;

DELIMITER ;;
CREATE TRIGGER logg_insert
AFTER UPDATE
ON scooter FOR EACH ROW -- chech each table row
BEGIN
    -- if a customer is assigned to scooter
    IF (
        OLD.customer_id IS NULL AND
        NOT NEW.customer_id IS NULL
        ) THEN
        
        -- insert new entry into logg table user, scooter, start time, lat, lot
        INSERT INTO logg (customer_id, scooter_id, start_time, start_lat, start_lon, total_cost)
-- FEL HÄR?
        VALUES (NEW.customer_id, NEW.id, NOW(), OLD.lat_pos, OLD.lon_pos, @start_cost);


    END IF;
END
;;
DELIMITER ;
```

`@start_cost` används i INSERT-kommandot, men jag hittar inget `SET @start_cost` tidigare i skriptet. Kanske kommer värdet att sättas ändå på något vis, men kan behöva förtydligas i en kommentar i DDL-skriptet så att vi vet hur/var vi ska debugga eller uppdatera vid behov.

**Comment by joki20** [comment]
Jag har i INSERT INTO tagit bort total_cost och från VALUES @start_cost.
Istället definierat total_cost i logg-tabellen till DECIMAL(7,2) DEFAULT 0 (eftersom resan kostar +2.50 per minut så är det två decimaler)
