### ISSUE TITLE
Bonus för att parkera vid laddningsstation, eller bara 'station'/parkeringsplats i allmänhet?

### ISSUE THREAD

**Issue by datalowe** [joki20/pattern-db#8]
I [ddl.sql](https://github.com/joki20/pattern-db/blob/master/sql-scripts/ddl.sql#L192) finns just nu i koden till triggern `logg_update` följande (lite textvägg här, scrolla förbi och läs vidare):

```sql
        -- PARKING AT A CHARGING STATION OR A ZONE
        --
        -- check if parked at a STATION, sets 0 or 1
        SET @ends_station = (
            SELECT EXISTS (
                SELECT * FROM station
                WHERE
                    charge = 1 -- indicates station
                AND
                    ABS(NEW.lat_pos-lat_center) <= radius
                AND
                    ABS(NEW.lat_pos-lat_center) <= radius
            )
		);
        -- check if parked within radius of any station but NOT at a station, sets 0 or 1
        SET @ends_zone = (
            SELECT EXISTS (
                SELECT * FROM station
                WHERE
                    charge = 0 -- indicates zone
                AND
                    ABS(NEW.lat_pos-lat_center) <= radius
                AND
                    ABS(NEW.lon_pos-lat_center) <= radius
            )
        );


        -- PAYMENT
        --
        -- INVOICE
        IF (SELECT payment_terms FROM customer WHERE id = OLD.customer_id) = 'invoice' THEN
        -- if scooter was collected outside allowed zone and parked near charging station or zone, give discount
            IF @started_outside_zone = 1 AND (@ends_station = 1 OR @ends_zone = 1) THEN
                SET @start_cost = @start_cost - 10; -- 10 kr discount
            END IF;

            -- if ending at a station, add station cost
            IF @ends_station = 1 THEN
                SET @total_cost = @start_cost + @travel_cost + @parking_cost_station;
            -- if ending in a zone but not at a station, add zone cost
            ELSEIF @ends_zone = 1 THEN
                SET @total_cost = @start_cost + @travel_cost + @parking_cost_zone;
```

Det viktiga är att prissättningen hanteras olika beroende på om resan slutar vid en laddningsstation eller en vanlig 'station'/parkeringsplats. `station` representerar ju parkeringsplatser i allmänhet, där de med `charge` satt till 1 specifikt representerar parkeringsplatser som har laddningsapparater.

I [kravspecifikationen för kursen (s. 4)](https://github.com/joki20/pattern-db/files/7513547/2021-11-03.Kravspecifikation.Svenska.Elsparkcyklar.AB.pdf) står att:

> 8. Varje resa som en kund gör kostar pengar, dels en fast taxa och en rörlig taxa per
tidsenhet och en taxa beroende av var de parkerar. 
> 9. Om en kund tar en cykel som står på fri parkering - och lämnar på en definierad
parkering - så blir startavgiften lite lägre

Det låter då som att det enda som spelar roll för prissättningen är om elsparkcykeln lämnas (resan slutar) vid en parkering, alltså innanför radien av en 'station', vare sig den har laddningsapparater eller inte.

Har jag missförstått? Annars kan vi ju behandla alla 'stationer' likadant här helt enkelt.

**Comment by jannikarlsson** [comment]
Jag tror att du har förstått rätt och tycker att de kan slås ihop. Vi kanske kan ta med det i diskussion om zonernas vara eller icke vara i morgon?
